#!/usr/bin/env bash

MAVEN_VERSION=3.6.3

sudo amazon-linux-extras install java-openjdk11

sudo mkdir -p /usr/share/maven
sudo curl -fsSL https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    | tar -xzC /usr/share/maven --strip-components=1
sudo ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

export MAVEN_HOME=/usr/share/maven
